version: '3.8'

services:

  anzctr:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-anzctr
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100116", "-a", "2"]

  biolincc:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-biolincc
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "101900", "-a", "2" ]

  braz:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-braz
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100117, 100119, 100122, 100129, 109108", "-a", "2" ]

  chictr:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-chictr
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100118", "-a", "2" ]

  ctg:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-ctg
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100120", "-a", "2" ]

  drks:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-drks
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100124", "-a", "2" ]

  euctr:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-euctr
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100123", "-a", "2" ]

  isrctn:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-isrctn
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100126", "-a", "2" ]

  japctr:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-japctr
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100127", "-a", "2" ]

  lebctr:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-lebctr
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100125,100128,100130,100131,101989", "-a", "2" ]

  nntr:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-nntr
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100132", "-a", "2" ]

  pubmed:
    image: mdr-coder-dotnet8
    container_name: mdr-coder-pubmed
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Coder.dll", "-s", "100135", "-a", "2" ]

  yoda:
    image: mdr-harvester-dotnet8
    container_name: mdr-harvester-yoda
    volumes:
      - $HOME/MDR_Logs_Docker_Volume:/app/MDR_Logs
      - $HOME/MDR_Test:/app/test
      - $HOME/MDR_Sources:/app/MDR_Sources
      - $HOME/MDR_Data:/app/MDR_Data
    command: [ "dotnet", "MDR_Harvester.dll", "-s", "101901", "-a", "2" ]